# -*- coding: utf-8 -*-
"""Image_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hua5sPaAUgGZv4rXHigrG9m2rPyDfkNO
"""

pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/techsash/waste-classification-data")

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os

# Set up paths to the train and test directories

base_dir = "/content/waste-classification-data/DATASET" # Remove the trailing /
train_dir = os.path.join(base_dir, "TRAIN") # Use os.path.join for platform independence
test_dir = os.path.join(base_dir, "TEST") # Use os.path.join for platform independence

# Use ImageDataGenerator to prepare the data for training and testing
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

# Display sample images from each clas
plt.figure(figsize=(10, 5))
for i, (image, label) in enumerate(train_data):  # Use enumerate and _next_ implicitly
    if i >= 4:  # Limit to 4 images
        break
    plt.subplot(1, 4, i + 1)
    plt.imshow(image[0])
    plt.title("Class: " + ("Organic" if label[0] == 0 else "Recyclable"))
    plt.axis('off')
plt.suptitle("Sample Images from Each Class")
plt.show()

mobilenet_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
mobilenet_model.trainable = False  # Freeze base model layers

# Add custom layers for classification
model = tf.keras.Sequential([
    mobilenet_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# We start with a pre-trained MobileNet model, adding layers to classify waste images into O or R.

history = model.fit(
    train_data,
    validation_data=test_data,
    epochs=8  # start with 8; increase later if accuracy is still climbing
)

# WHY epochs=8: with a frozen pretrained base, you only need to train
# the small classification head (GlobalAveragePooling2D + Dense layer).
# That converges fast -- 5-10 epochs is normal. Training from scratch
# would need 30-50+ epochs, which is the whole point of transfer learning.

# ---- CELL 7: Evaluate on test set ----
test_loss, test_accuracy = model.evaluate(test_data)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# This gives you the headline number for your resume bullet.

# ---- CELL 8: Plot training curves (shows you understand overfitting/underfitting) ----
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# WHY this matters: if train accuracy keeps rising but validation
# accuracy flattens or drops, that's overfitting. Being able to point
# at this graph and explain it in an interview is a strong signal.

# ---- CELL 9: Detailed metrics -- precision, recall, F1, confusion matrix ----
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Get true labels and predictions for the full test set
test_data.reset()  # make sure generator starts from the beginning
y_true = test_data.classes  # actual labels Keras assigned
y_pred_probs = model.predict(test_data)
y_pred = (y_pred_probs > 0.5).astype(int).flatten()  # threshold sigmoid output at 0.5

class_names = list(test_data.class_indices.keys())  # e.g. ['O', 'R']

print(classification_report(y_true, y_pred, target_names=class_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# WHY precision/recall matter MORE than accuracy here:
# If your dataset has more Organic than Recyclable images (check the
# 22,564 train count split), accuracy alone can be misleading.
# Example: if 70% of images are Organic, a lazy model that always
# predicts "Organic" gets 70% accuracy while being useless.
# Precision/recall per class exposes that kind of failure -- this is
# exactly the kind of thing an interviewer probes for.

# ---- CELL 10 (optional but strong): Save the model ----
model.save('waste_classifier_mobilenetv2.h5')
print("Model saved!")

# Lets you reload it later without retraining, and you can mention
# in your README that the trained model is included/loadable.